// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace MC.eSIS.Database.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixUserRequiredField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixUserRequiredField));
        
        string IMigrationMetadata.Id
        {
            get { return "201602150502020_FixUserRequiredField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
