image: "ruby:2.2.4"

variables:
  HEROKU_API_KEY: "e5f13cc6-c576-46fe-a13c-c9dd9e972e5b"
  HEROKU_PRODUCTION_APP_NAME: "genesis-itst"

cache:
  paths:
    - vendor/

stages:
  - build

build:
  stage: build
  script:
  - gem install bundler
  - bundle install --path vendor --without development test
  #- bundle exec rails db:migrate RAILS_ENV=production
  #- bundle exec rails c production