default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: genesis
  username: postgres
  password: Nad324!!
  host: localhost
  port: 5432

test:
  <<: *default
  host: ec2-54-235-179-112.compute-1.amazonaws.com
  database: db3tt9q656nvn2
  user: ezkdcnkrlkaojz
  password: "D4skjsqz85tjsbbr-RYqtqpnO7"
  url: "postgres://ezkdcnkrlkaojz:D4skjsqz85tjsbbr-RYqtqpnO7@ec2-54-235-179-112.compute-1.amazonaws.com/db3tt9q656nvn2"