module Genesis
  module ENUMS

    FULL_NAME_FORMAT = [LAST_FIRST = 1, FIRST_LAST = 2]
    ADDRESS_FORMAT = [WITH_LINE_BREAKS = 1, ONE_LINE = 2]
    SEX = [MALE = 'M', FEMALE = 'F']
    ACCOUNT_STATUS = [ANONYMOUS = 0, ACTIVE = 1, REGISTERED = 2, LOCKED = 3]
    ENROLLMENT_CODE = [ADD = 1, DROP = 2]

  end
end